### ISSUE TITLE
A partir d'un certain temps les synchronisations Vinted ne se font plus

### ISSUE THREAD

**Issue by JuraJour** [Androz2091/vinted-discord-bot#10]
Salut :)
Merci pour ton super travail.
Au début de l'exécution du script, tout fonctionne très bien et je reçois bien les articles.
Mais au bout d'un moment je ne reçois plus rien et dans la console les "Synchronisation à Vinted" ne s'affichent plus.

**Comment by Androz2091** [comment]
Salut !
Le problème doit être réglé, peux-tu réessayer ? merci !

**Comment by JuraJour** [comment]
D'accord, je regarde et je te redis.
Par contre je dois "npm i easy-json-database", c'est pas fait au début.
