### ISSUE TITLE
Problème Token Vinted

### ISSUE THREAD

**Issue by Lukas-Craft** [Androz2091/vinted-discord-bot#40]
![image](https://user-images.githubusercontent.com/69809621/178137235-41c155b9-4090-43f1-9c02-3757e3ed4049.png)
 Bonjour, à chaque fois que je lance le bot, il n'arrive pas à se connecter à vinted à l'aide du token. Quelqu'un peut m'aider ???

**Comment by siim0n** [comment]
Salut, j'avais trouvé la solution hier du coup, j'ai utilisé la version de Hyper beasts https://github.com/HyperBeats/vinted-api/blob/main/index.js mais j'ai du modifier le dockerfile pour l'utiliser à la place de celle installée par yarn install
Dis moi si t'as encore besoin d'aide.

**Comment by Lukas-Craft** [comment]
Salut, merci pour l'info mais Ducoup comment t'a fait pour l'intégrer pour pas que je détruit tout ce que j'ai fait sachant que sa tient pas des masses.

**Comment by siim0n** [comment]
`FROM node:17-alpine3.12

RUN mkdir -p /home/app

COPY ./app /home/app

WORKDIR /home/app

RUN yarn install

RUN rm -rf /node_modules/vinted-api/index.js

RUN \cp -r vinted-api-main/index.js node_modules/vinted-api/index.js -f

RUN yarn build

CMD [ "yarn", "start" ]
`
J'ai mis ça dans le docker file, et j'ai donc mis tout le dossier de hyper beasts pour pas m'embêter

**Comment by Lukas-Craft** [comment]
Merci beaucoup

**Comment by Lukas-Craft** [comment]
Par contre le dossier node_modules tu l'a crée à la main ou il était déjà

**Comment by siim0n** [comment]
le dossier node modules est créé par le yarn install avant
