### ISSUE TITLE
Problème Sync is running

### ISSUE THREAD

**Issue by Keunotor** [Androz2091/vinted-discord-bot#5]
Bonjour, après avoir suivi les instructions pour configurer le bot, un problème survient. Après avoir tapé la commande node index.js , le bot se connecte bel et bien sur Discord, mais le message Sync is running apparaît en boucle. Quand je vais sur mon serveur discord, aucune commande du bot ne marche. 

J'ai essayé de régler ce problème en utilisant Node.js 16.4.0, et Node.js 14.17.1, mais c'est la même chose.

**Comment by Androz2091** [comment]
Réglé avec la nouvelle version
