### ISSUE TITLE
Recherche à partir de l'URL

### ISSUE THREAD

**Issue by FriedmanLunique** [Androz2091/vinted-discord-bot#8]
Il serait intéressant avec le bot de pouvoir effectuer des recherches à partir de l'URL vinted qui contient tous les critères en 1 au lieu de demander les critères 1 à 1 au bot. Cela permet d'avoir des recherches plus précises et d'éviter des annonces indésirées [certains mettent des #nike (imaginons que notre recherche est "pull nike") dans leur annonce alors un pull Kiabi par exemple et le bot détectant le mot "nike" va nous envoyer l'annonce]

L'idée serait que le bot nous demande seulement l'url comme sur la photo ci-dessous car l'url contient tous les critères que l'on sélectionne.

Merci :)

![image](https://user-images.githubusercontent.com/88970128/129482325-55b8eda7-9376-4fed-8ac4-0d815412fc01.png)

**Comment by Androz2091** [comment]
C'est ajouté
