### ISSUE TITLE
BUG de sync pour les commandes

### ISSUE THREAD

**Issue by Oilidlj** [Androz2091/vinted-discord-bot#9]
node index.js
Logged in as #####!
2021-09-05T06:30:38.593Z | Sync is running...
/mnt/c/Users/ ####/OneDrive/Desktop/vinted-discord-bot-main/node_modules/discord-sync-commands/index.js:12  
    const currentCommands = await client.application.commands.fetch(options.guildId && { guildId: options.guildId });
                                                     ^
TypeError: Cannot read property 'commands' of undefined
    at module.exports (/mnt/c/Users/####/OneDrive/Desktop/vinted-discord-bot-main/node_modules/discord-sync-commands/index.js:12:54)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Androz2091** [comment]
Est-ce que ce bug survient souvent, à chaque lancement du bot, ou seulement de temps en temps ?

**Comment by Oilidlj** [comment]
Bah, c'est là première fois que je lance le bot donc je ne saurais pas te dire. Et je n'ai toujours pas réussi à le faire fonctionner.

**Comment by Oilidlj** [comment]
Merde excuse moi, je suis fatigué oui à chaque lancement du bot !

**Comment by Androz2091** [comment]
D'accord, je peux t'aider sur Discord en vocal si tu veux (https://androz2091.fr/discord), ce sera plus simple de trouver une solution

**Comment by Androz2091** [comment]
Pb réglé sur Discord
